<?php
declare(strict_types=1);

namespace App\Services\Documents;

/**
 * The two documents a patient walks out with (§4, §6).
 *
 * Both are laid out here rather than in a template file because they are not
 * pages: they are a fixed arrangement of facts that a pharmacist or a tax
 * inspector reads in a fixed order, and the layout code is the specification
 * of that order.
 *
 * Nothing here computes anything. Every figure is passed in already decided by
 * InvoiceService, so a document can never quote a different total from the
 * ledger it was printed from.
 */
final class ClinicDocuments
{
    private const INK    = [0.06, 0.11, 0.18];
    private const MUTED  = [0.49, 0.53, 0.60];
    private const ACCENT = [0.04, 0.39, 0.52];
    private const RULE   = [0.89, 0.91, 0.94];
    private const BAND   = [0.94, 0.96, 0.98];

    private const LEFT  = 48.0;
    private const RIGHT = 547.0;

    /**
     * @param array<string,mixed> $rx      the prescription, as the API returns it
     * @param array<string,mixed> $clinic  organization settings
     */
    public static function prescription(array $rx, array $clinic): string
    {
        $pdf = new Pdf();
        $y   = self::header($pdf, $clinic, 'PRESCRIPTION', (string) $rx['prescription_no']);

        // Who it is for, and who wrote it — side by side, because a pharmacist
        // checks both before anything else.
        $y = self::twoColumns($pdf, $y, [
            'Patient'       => (string) $rx['patient_name'],
            'Patient ID'    => (string) $rx['mrn'],
            'Age / gender'  => trim(($rx['patient_age'] ?? '—') . ' / ' . ($rx['gender'] ?? '—')),
        ], [
            'Doctor'    => (string) $rx['doctor_name'],
            'Specialty' => (string) ($rx['specialty'] ?? '—'),
            'Issued'    => self::date($rx['issued_at'] ?? $rx['created_at'] ?? null),
        ]);

        if (!empty($rx['diagnoses'])) {
            $names = array_map(
                static fn(array $d): string => (string) $d['description'],
                $rx['diagnoses'],
            );
            $pdf->text('Diagnosis', self::LEFT, $y, 9, 'bold', self::MUTED);
            $y = $pdf->paragraph(implode('; ', $names), self::LEFT, $y + 14, self::RIGHT - self::LEFT, 10.5);
            $y += 6;
        }

        // The medicines. The big Rx is what a pharmacist's eye goes to.
        $pdf->text('Rx', self::LEFT, $y + 18, 22, 'bold', self::ACCENT);
        $y += 34;

        foreach ($rx['items'] ?? [] as $i => $item) {
            $pdf->text(
                ($i + 1) . '.  ' . (string) $item['medication_name'],
                self::LEFT, $y, 12, 'bold',
            );
            $y += 15;

            $detail = array_filter([
                $item['dosage'] ?? null,
                $item['frequency'] ?? null,
                $item['duration'] ?? null,
            ]);
            if ($detail !== []) {
                $pdf->text(implode('   ·   ', $detail), self::LEFT + 18, $y, 10.5, 'regular', self::INK);
                $y += 14;
            }

            if (!empty($item['instructions'])) {
                $y = $pdf->paragraph(
                    (string) $item['instructions'],
                    self::LEFT + 18, $y, self::RIGHT - self::LEFT - 18, 9.5,
                );
            }

            $y += 8;

            if ($y > 700) {           // keep clear of the signature block
                $pdf->newPage();
                $y = 60.0;
            }
        }

        if (!empty($rx['general_advice'])) {
            $y += 4;
            $pdf->line(self::LEFT, $y, self::RIGHT, $y, 0.6, self::RULE);
            $y += 16;
            $pdf->text('Advice', self::LEFT, $y, 9, 'bold', self::MUTED);
            $y = $pdf->paragraph(
                (string) $rx['general_advice'],
                self::LEFT, $y + 14, self::RIGHT - self::LEFT, 10.5,
            );
        }

        self::signature($pdf, (string) $rx['doctor_name'], (string) ($rx['qualification'] ?? ''));
        self::footer($pdf, $clinic, 'This prescription was generated by MediFlow.');

        return $pdf->render();
    }

    /**
     * @param array<string,mixed> $invoice the invoice with its items
     * @param array<string,mixed> $clinic  organization settings
     */
    public static function invoice(array $invoice, array $clinic): string
    {
        $pdf      = new Pdf();
        $currency = (string) ($invoice['currency_code'] ?? '');
        $y        = self::header($pdf, $clinic, 'INVOICE', (string) $invoice['invoice_no']);

        $y = self::twoColumns($pdf, $y, [
            'Billed to'  => (string) $invoice['patient_name'],
            'Patient ID' => (string) ($invoice['mrn'] ?? '—'),
        ], [
            'Issued'   => self::date($invoice['issue_date'] ?? $invoice['created_at'] ?? null),
            'Due'      => self::date($invoice['due_date'] ?? null),
            'Status'   => strtoupper(str_replace('_', ' ', (string) $invoice['status'])),
        ]);

        // ---- the lines ----
        $pdf->fill(self::LEFT, $y - 11, self::RIGHT - self::LEFT, 20, self::BAND);
        $pdf->text('DESCRIPTION', self::LEFT + 8, $y + 3, 8.5, 'bold', self::MUTED);
        $pdf->textRight('QTY', self::LEFT + 350, $y + 3, 8.5, 'bold');
        $pdf->textRight('UNIT', self::LEFT + 420, $y + 3, 8.5, 'bold');
        $pdf->textRight('AMOUNT', self::RIGHT - 8, $y + 3, 8.5, 'bold');
        $y += 26;

        foreach ($invoice['items'] ?? [] as $item) {
            $pdf->text((string) $item['description'], self::LEFT + 8, $y, 10);
            $pdf->textRight(rtrim(rtrim((string) $item['quantity'], '0'), '.') ?: '1',
                self::LEFT + 350, $y, 10);
            $pdf->textRight(self::money($item['unit_price'] ?? 0), self::LEFT + 420, $y, 10);
            $pdf->textRight(self::money($item['line_total'] ?? 0), self::RIGHT - 8, $y, 10);

            if (!empty($item['service_code'])) {
                $pdf->text((string) $item['service_code'], self::LEFT + 8, $y + 11, 8, 'mono', self::MUTED);
                $y += 10;
            }

            $y += 18;
            $pdf->line(self::LEFT, $y - 6, self::RIGHT, $y - 6, 0.4, self::RULE);

            if ($y > 640) {
                $pdf->newPage();
                $y = 60.0;
            }
        }

        // ---- totals ----
        $y += 10;
        $totals = [
            ['Subtotal', $invoice['subtotal'] ?? 0, false],
        ];
        if ((float) ($invoice['discount_total'] ?? 0) > 0) {
            $totals[] = ['Discount', '-' . self::money($invoice['discount_total']), true];
        }
        if ((float) ($invoice['tax_total'] ?? 0) > 0) {
            $totals[] = ['Tax', $invoice['tax_total'], false];
        }

        foreach ($totals as [$label, $value, $preformatted]) {
            $pdf->textRight($label, self::RIGHT - 110, $y, 10, 'regular');
            $pdf->textRight($preformatted ? (string) $value : self::money($value), self::RIGHT - 8, $y, 10);
            $y += 16;
        }

        $pdf->fill(self::RIGHT - 250, $y - 12, 250, 26, self::BAND);
        $pdf->textRight('TOTAL ' . $currency, self::RIGHT - 110, $y + 3, 11, 'bold');
        $pdf->textRight(self::money($invoice['grand_total'] ?? 0), self::RIGHT - 8, $y + 3, 12, 'bold');
        $y += 34;

        if ((float) ($invoice['paid_total'] ?? 0) > 0) {
            $pdf->textRight('Paid', self::RIGHT - 110, $y, 10);
            $pdf->textRight(self::money($invoice['paid_total']), self::RIGHT - 8, $y, 10);
            $y += 16;
        }

        $due = (float) ($invoice['balance_due'] ?? 0);
        $pdf->textRight('Balance due', self::RIGHT - 110, $y, 11, 'bold');
        $pdf->textRight(
            self::money($invoice['balance_due'] ?? 0),
            self::RIGHT - 8, $y, 11, 'bold',
        );

        if ($due <= 0) {
            $pdf->text('PAID IN FULL', self::LEFT, $y, 13, 'bold', [0.06, 0.54, 0.37]);
        }

        if (!empty($invoice['notes'])) {
            $pdf->paragraph((string) $invoice['notes'], self::LEFT, $y + 40, 300, 9.5);
        }

        self::footer($pdf, $clinic, 'Computer-generated invoice — valid without a signature.');

        return $pdf->render();
    }

    // ---------------------------------------------------------------

    /** @param array<string,mixed> $clinic */
    private static function header(Pdf $pdf, array $clinic, string $kind, string $number): float
    {
        $pdf->text((string) ($clinic['name'] ?? 'Clinic'), self::LEFT, 56, 17, 'bold', self::ACCENT);

        $address = array_filter([
            $clinic['address'] ?? null,
            $clinic['city'] ?? null,
            $clinic['country_name'] ?? null,
        ]);
        if ($address !== []) {
            $pdf->text(implode(', ', $address), self::LEFT, 74, 9, 'regular', self::MUTED);
        }

        $contact = array_filter([$clinic['phone'] ?? null, $clinic['email'] ?? null]);
        if ($contact !== []) {
            $pdf->text(implode('  ·  ', $contact), self::LEFT, 87, 9, 'regular', self::MUTED);
        }

        $pdf->textRight($kind, self::RIGHT, 58, 15, 'bold');
        $pdf->textRight($number, self::RIGHT, 76, 11, 'mono');

        $pdf->line(self::LEFT, 100, self::RIGHT, 100, 1.0, self::ACCENT);

        return 124.0;
    }

    /**
     * @param array<string,string> $left
     * @param array<string,string> $right
     */
    private static function twoColumns(Pdf $pdf, float $y, array $left, array $right): float
    {
        $start = $y;
        foreach ($left as $label => $value) {
            $pdf->text($label, self::LEFT, $y, 8.5, 'regular', self::MUTED);
            $pdf->text($value, self::LEFT, $y + 13, 11, 'bold');
            $y += 32;
        }

        $rightY = $start;
        foreach ($right as $label => $value) {
            $pdf->text($label, self::LEFT + 300, $rightY, 8.5, 'regular', self::MUTED);
            $pdf->text($value, self::LEFT + 300, $rightY + 13, 11, 'bold');
            $rightY += 32;
        }

        $y = max($y, $rightY) + 4;
        $pdf->line(self::LEFT, $y, self::RIGHT, $y, 0.6, self::RULE);

        return $y + 22;
    }

    private static function signature(Pdf $pdf, string $doctor, string $qualification): void
    {
        $pdf->line(self::RIGHT - 180, 742, self::RIGHT, 742, 0.6, self::RULE);
        $pdf->text($doctor, self::RIGHT - 180, 756, 10.5, 'bold');
        if ($qualification !== '') {
            $pdf->text($qualification, self::RIGHT - 180, 769, 9, 'regular', self::MUTED);
        }
    }

    /** @param array<string,mixed> $clinic */
    private static function footer(Pdf $pdf, array $clinic, string $note): void
    {
        $pdf->line(self::LEFT, 792, self::RIGHT, 792, 0.6, self::RULE);
        $pdf->text($note, self::LEFT, 806, 8, 'regular', self::MUTED);
        $pdf->textRight(
            'Printed ' . gmdate('d M Y H:i') . ' UTC',
            self::RIGHT, 806, 8, 'regular',
        );
    }

    private static function money(mixed $value): string
    {
        return number_format((float) $value, 2, '.', ',');
    }

    private static function date(mixed $value): string
    {
        if (empty($value)) {
            return '—';
        }
        $ts = strtotime((string) $value);
        return $ts === false ? (string) $value : gmdate('d M Y', $ts);
    }
}
