<?php
declare(strict_types=1);

namespace App\Services\Documents;

use App\Core\Service;
use App\Repositories\ClinicalRepository;

/**
 * Keeping a document the system generated (§19, §26).
 *
 * Uploads already had a home: bytes to storage outside the webroot, metadata
 * and an access rule in medical_documents. Documents the system *prints* —
 * prescriptions and invoices — did not. They were rendered on demand every
 * time, and prescriptions.pdf_path and invoices.pdf_path sat empty on all 63
 * issued prescriptions and all 528 issued invoices.
 *
 * Rendering on demand is right for a draft: a stored copy of something still
 * being edited is a second version of the truth waiting to disagree with the
 * first. It is wrong the moment a document is ISSUED. An issued invoice is
 * immutable by design here — the code refuses to edit one — and the patient
 * or the pharmacy is holding a specific piece of paper. Re-rendering it later
 * from current data answers "what would we print today", which is not the same
 * question as "what did we hand them".
 *
 * So: drafts render, issued documents are kept. The checksum is what makes the
 * kept copy worth having — it can be shown to be the same bytes.
 */
final class DocumentStore extends Service
{
    /**
     * Write generated bytes to storage and record them.
     *
     * @param array<string,mixed> $meta patient_id, category, title,
     *                                  encounter_id?, visibility?
     * @return array<string,mixed> the medical_documents row
     */
    public function keep(array $meta, string $bytes): array
    {
        $org    = $this->requireOrganization();
        $config = $GLOBALS['__config']['storage'] ?? [];

        // Same scheme as an upload: partitioned by tenant, with a generated
        // name. Nothing from a request reaches the path.
        $relative = sprintf('documents/%d/%s.pdf', $org, bin2hex(random_bytes(16)));
        $absolute = rtrim((string) ($config['root'] ?? ''), '/\\') . '/' . $relative;

        $directory = dirname($absolute);
        if (!is_dir($directory) && !mkdir($directory, 0775, true) && !is_dir($directory)) {
            throw new \RuntimeException('Could not create the storage directory.');
        }
        if (file_put_contents($absolute, $bytes) === false) {
            throw new \RuntimeException('Could not write the generated document.');
        }

        return (new ClinicalRepository())->forOrganization($org)->addDocument([
            'patient_id'      => $meta['patient_id'],
            'encounter_id'    => $meta['encounter_id'] ?? null,
            'category'        => $meta['category'],
            'title'           => $meta['title'],
            'storage_path'    => $relative,
            'mime_type'       => 'application/pdf',
            'size_bytes'      => strlen($bytes),
            'checksum_sha256' => hash('sha256', $bytes),
            // A document the clinic issued TO the patient is theirs to read.
            'visibility'      => $meta['visibility'] ?? 'patient_visible',
        ], $this->actorId);
    }

    /**
     * Keep a document, but never at the cost of the thing it describes.
     *
     * Issuing an invoice must not fail because a disk is full. The row is the
     * record; the PDF is a copy of it, and a missing copy can be regenerated
     * while a refused issue cannot be un-refused for a patient standing at
     * the desk.
     *
     * @param array<string,mixed> $meta
     * @return array<string,mixed>|null the row, or null if it could not be kept
     */
    public function tryKeep(array $meta, string $bytes): ?array
    {
        try {
            return $this->keep($meta, $bytes);
        } catch (\Throwable $e) {
            error_log('[documents] could not keep a generated document: ' . $e->getMessage());
            return null;
        }
    }
}
