<?php
declare(strict_types=1);

namespace App\Core;

/**
 * Base controller.
 *
 * Per §12 a controller does exactly three things:
 *   1. validate the request shape,
 *   2. hand it to a service,
 *   3. return the service's result as JSON.
 *
 * It contains NO SQL and NO business rules. If a controller method grows
 * past ~15 lines, the logic belongs in a service.
 */
abstract class Controller
{
    /**
     * Validate the request body against $rules and return the clean values.
     *
     * @param array<string,string> $rules
     * @return array<string,mixed>
     */
    protected function validate(Request $request, array $rules): array
    {
        return Validator::run($request->body, $rules);
    }

    /**
     * Validate the query string (list filters, pagination).
     *
     * @param array<string,string> $rules
     * @return array<string,mixed>
     */
    protected function validateQuery(Request $request, array $rules): array
    {
        return Validator::run($request->query, $rules);
    }

    /** @param array<string,mixed>|null $meta */
    protected function ok(mixed $data, ?array $meta = null): never
    {
        Response::success($data, 200, $meta);
    }

    protected function created(mixed $data): never
    {
        Response::success($data, 201);
    }

    protected function noContent(): never
    {
        Response::json(null, 204);
    }

    /**
     * Send generated bytes — a PDF — instead of the JSON envelope.
     *
     * `inline` so a phone or a browser shows it rather than dropping a file in
     * Downloads; anyone who wants it saved can still save it from the viewer.
     */
    protected function file(string $bytes, string $filename, string $mime = 'application/pdf'): never
    {
        header('Content-Type: ' . $mime);
        header('Content-Length: ' . (string) strlen($bytes));
        header('Content-Disposition: inline; filename="' . str_replace('"', '', $filename) . '"');
        // A clinical document must not be served from a stale cache after the
        // record behind it changed.
        header('Cache-Control: no-store, private');
        echo $bytes;
        exit;
    }

    /**
     * Assert the caller holds a permission in the active tenant, else 403.
     * Used for checks that are finer-grained than the route middleware.
     */
    protected function authorize(Request $request, string $permission): void
    {
        if (!$request->can($permission)) {
            throw new ForbiddenException("Missing permission: $permission");
        }
    }

    /** Standard pagination inputs, clamped to sane bounds. */
    protected function pagination(Request $request): array
    {
        $page    = max(1, (int) ($request->query['page'] ?? 1));
        $perPage = (int) ($request->query['per_page'] ?? 25);
        return [$page, max(1, min(100, $perPage))];
    }
}
